"use strict";
/*
 * Generate a white "backing" that fills ONLY the enclosed transparent holes in
 * lola.svg (e.g. the front-leg interiors) — never the outside or the gap
 * between the legs. Method:
 *   1. render Lola on a pure-magenta background (a color not used in the art)
 *   2. flood-fill the magenta from the image borders -> "exterior"
 *   3. magenta pixels NOT reached = enclosed holes -> paint white
 *   4. dilate a couple px so the fill tucks under the black outline
 * Output: src/shared/lola-fill.js exporting { dataUrl } (a PNG data URI).
 */
const { app, BrowserWindow, nativeImage } = require("electron");
const path = require("path");
const fs = require("fs");
const svg = require("../src/shared/lola.js").svg;

const W = 1000, H = 849;

app.disableHardwareAcceleration();
app.whenReady().then(async () => {
  const win = new BrowserWindow({ width: W, height: H, show: false, webPreferences: { offscreen: true } });
  const html = `<!DOCTYPE html><html><head><meta charset="utf-8"><style>
    html,body{margin:0;background:#ff00ff}
    svg{width:${W}px;height:${H}px;display:block}
  </style></head><body>${svg}</body></html>`;
  await win.loadURL("data:text/html;charset=utf-8," + encodeURIComponent(html));
  await new Promise((r) => setTimeout(r, 500));
  const img = await win.webContents.capturePage();
  const size = img.getSize();
  const w = size.width, h = size.height;
  const buf = img.getBitmap(); // BGRA
  win.destroy();

  const N = w * h;
  const isBg = new Uint8Array(N); // magenta-ish background/hole pixel
  for (let p = 0; p < N; p++) {
    const b = buf[p * 4], g = buf[p * 4 + 1], r = buf[p * 4 + 2];
    if (r > 140 && b > 140 && g < 130) isBg[p] = 1;
  }

  // flood-fill background from all border pixels -> exterior
  const ext = new Uint8Array(N);
  const stack = [];
  for (let x = 0; x < w; x++) { stack.push(x); stack.push((h - 1) * w + x); }
  for (let y = 0; y < h; y++) { stack.push(y * w); stack.push(y * w + w - 1); }
  while (stack.length) {
    const p = stack.pop();
    if (ext[p] || !isBg[p]) continue;
    ext[p] = 1;
    const x = p % w, y = (p - x) / w;
    if (x > 0) stack.push(p - 1);
    if (x < w - 1) stack.push(p + 1);
    if (y > 0) stack.push(p - w);
    if (y < h - 1) stack.push(p + w);
  }

  // enclosed holes = background AND not exterior
  let hole = new Uint8Array(N);
  let holeCount = 0;
  for (let p = 0; p < N; p++) if (isBg[p] && !ext[p]) { hole[p] = 1; holeCount++; }

  // dilate the hole mask a few px so it slips under the outline (no hairline)
  function dilate(src) {
    const dst = new Uint8Array(N);
    for (let y = 0; y < h; y++) {
      for (let x = 0; x < w; x++) {
        const p = y * w + x;
        if (src[p] ||
          (x > 0 && src[p - 1]) || (x < w - 1 && src[p + 1]) ||
          (y > 0 && src[p - w]) || (y < h - 1 && src[p + w])) dst[p] = 1;
      }
    }
    return dst;
  }
  hole = dilate(dilate(dilate(hole)));

  // build white-on-transparent BGRA
  const out = Buffer.alloc(N * 4);
  for (let p = 0; p < N; p++) {
    if (hole[p]) { out[p * 4] = 255; out[p * 4 + 1] = 255; out[p * 4 + 2] = 255; out[p * 4 + 3] = 255; }
  }
  const png = nativeImage.createFromBitmap(out, { width: w, height: h }).toPNG();
  const dataUrl = "data:image/png;base64," + png.toString("base64");

  const mod = `/*
 * Pixll — white backing that fills the enclosed transparent holes in Lola's
 * trace (front legs etc). Generated by tools/make-fill.cjs — do not hand-edit.
 * Rendered UNDERNEATH lola.svg by pet-render.js.
 */
(function (root) {
  root.PixllLolaFill = { dataUrl: ${JSON.stringify(dataUrl)}, w: ${W}, h: ${H} };
  if (typeof module !== "undefined" && module.exports) module.exports = root.PixllLolaFill;
})(typeof window !== "undefined" ? window : globalThis);
`;
  fs.writeFileSync(path.join(__dirname, "..", "src", "shared", "lola-fill.js"), mod, "utf8");
  console.log(`holes: ${holeCount}px at ${w}x${h}; wrote src/shared/lola-fill.js (${Math.round(png.length / 1024)} KB)`);
  app.quit();
});
